[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["Pavel Mametev <pavelmametev@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.7"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
